#! /bin/sh
# /etc/init.d/initmbox 
# Provides:          noip
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Simple script to start a program at boot
# Description:       A simple script from www.stuffaboutcode.com which will start / stop a program a boot / shutdown.
### END INIT INFO

# If you want a command to always run, put it here

# Carry out specific functions when asked to by the system
start_mbox() {
  server="10.0.0.78"
  flag=0
  echo $1
  count=0
  while true; do
  #ip=`ifconfig | grep -A 1 $1 | tail -1 | cut -d ':' -f 2 | cut -d ' ' -f 1`
  ip=`ifconfig eth0 | grep 'inet addr:' | cut -d: -f2 | awk '{print $1}'`
  gw=`route -n | grep 'UG[ \t]' | awk '{print $2}'`
  mac_addr=`cat /sys/class/net/eth0/address | sed 's/\://g' | tr 'a-z' 'A-Z'`
  echo "ip=$ip" >> /var/log/user.log
  echo "netmask=$mask" >> /var/log/user.log
  echo "gateway=$gw" >> /var/log/user.log
  echo "server=$server" >> /var/log/user.log

# -q quiet
# -c nb of pings to perform
  ping -c 2 $server > /dev/null

  if [ $? -eq 0 ]
  then
        echo "network is ok" >> /var/log/user.log
        flag=1
  else
        count=`expr $count + 1`
        echo "count=$count" >> /var/log/user.log
        echo "network is not available" >> /var/log/user.log
        sleep 5
        if [ $count -eq 5 ]
        then
                echo "start app failed -> reboot" >> /var/log/user.log
                reboot
        fi
  fi
  if [ $flag -eq 1 ]
  then
        count=0
        if [ -f /etc/mbox.cfg ]
  then
                Mbox &
        else
                Mbox $mac_addr &
        fi
        wait
        echo "started Mbox" > /dev/ttyAMA0
        killall Mbox
        flag=0
  fi
  done

}
case "$1" in
  start)
    echo "Starting mbox"
    # run application you want to start
    start_mbox
    ;;
  stop)
    echo "Stopping mbox"
    # kill application you want to stop
    killall Mbox
    killall startMediaHub.sh
    ;;
  *)
    echo "Usage: /etc/init.d/noip {start|stop}"
    exit 1
    ;;
esac

exit 0
